export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CHANGE_THEME = 'CHANGE-THEME';
export  const ENABLE_BUTTONS = 'ENABLE_BUTTONS';
export  const DISABLE_BUTTONS = 'DISABLE_BUTTONS';

